# This is a config for E2B sandbox template.
# You can use template ID (19yfif5g41gk0gvjcxp9) or template name (web-weave-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("web-weave-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("web-weave-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('web-weave-test-2')

team_id = "d1ccd07f-dfdd-4737-9a86-099aeff2aeb9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "web-weave-test-2"
template_id = "19yfif5g41gk0gvjcxp9"
